export default {
  gender: {
    male: 'Male',
    female: 'Female',
    intersex: 'Intersex',
    transgender: 'Transgender',
  },
  sex: {
    male: 'Male',
    female: 'Female',
    intersex: 'Intersex',
    transgender: 'Trans',
  },
  tag: { 'sexual-assault': 'sexual assault' },
  user: {
    provider: 'Healthcare provider',
    associate: 'Associate',
    userManager: 'User manager',
    FormDesigner: 'Form designer',
    Researcher: 'Researcher',
  },
  form: {
    Yes: 'Yes',
    No: 'No',
    'select-value': 'Select a value',
    'other-details': 'Describe other optional details',
    'add-photo': 'Add a photo',
    'delete-photo': 'Delete photo',
    'mark-diagram': 'Annotate the diagram',
    'repeated-one-time-below': 'repeated one time below',
    'can-repeat-below': 'can repeat below',
    repeated: 'repeated',
    'times-below': 'times below',
    'repeat-number': 'number',
    'repeat-out-of': 'out of',
    'enter-date-time': 'Enter date and time',
    'enter-date': 'Enter date',
    'enter-number': 'Enter number',
    'enter-phone-number': 'Enter phone number',
    'enter-email': 'Enter email',
    'enter-text': 'Enter text',
    'enter-long-text': 'Enter long text',
    'enter-address': 'Enter address',
    'select-other-option': 'Select other option',
    'select-the-option': 'Select the option',
    'skip-question': 'Skip answering this question',
  },
}
