export default {
  languages: {
    en: 'English',
    fr: 'French',
  },
  gender: {
    male: 'Male',
    female: 'Female',
    intersex: 'Intersex',
    transgender: 'Transgender',
  },
  sex: {
    male: 'Male',
    female: 'Female',
    intersex: 'Intersex',
    transgender: 'Transgender',
  },
  tag: { 'sexual-assault': 'sexual assault' },
  heading: {
    name: 'Name',
    countryAndLanguage: 'Country & Language',
    lastChangedAndId: 'Last changed & ID',
    enabled: 'Enabled',
    usernameAndEmail: 'Enabled',
  },
  user: {
    Provider: 'Healthcare provider',
    Associate: 'Associate',
    Manager: 'Manager',
    FormDesigner: 'Form designer',
    Researcher: 'Researcher',
    'select-user-type': 'Select user type',
    'any-user-type': 'Any user type',
    'enter-location': 'Narrow by location',
    'any-location': 'Any location',
    'search-by': {
      username: 'Search username',
      email: 'Search email',
      'phone-number': 'Search phone #',
      name: 'Search name',
      'first-name': 'Search first name',
      'family-name': 'Search family name',
      'user-id-code': 'Search user ID code',
      select: 'Select search type',
    },
    filter: {
      'select-user-enabled': 'Enabled or disabled users',
      'any-is-user-enabled': 'All users',
      enabled: 'Enabled users',
      disabled: 'Disabled users',
    },
    'search-enter': 'Enter search text',
    'full-official-name': 'Full official name',
    'short-name': 'Short name',
    nickname: 'Nickname',
    email: 'Email address',
    'phone-number': 'Phone number',
    username: 'Username',
    address: 'Address',
    'user-type': 'User type',
    heading: {
      'official-id': 'Official ID',
      metadata: 'Metadata',
      bio: 'Bio',
    },
    'create-user': 'Create user',
    'disable-user': 'Disable user',
    'enable-user': 'Enable user',
    'submitting-user': 'Updating user',
    'submit-user': 'Update user',
    'submitted-user': 'Update user',
    'reset-password': 'Reset password',
    'password-reset': 'User password reset',
    'password-resetting': 'Resetting password',
    official_id_type: 'Official ID type',
    official_id_code: 'Official ID code',
    official_id_expires: 'ID expiration date',
    id: 'User ID code',
    'last-changed': 'Last changed',
    'created-on': 'Created on',
    'allowed-locations': 'Allowed locations',
    birthday: 'Birthday',
    'date-of-birth': 'Birthday',
    gender: 'Gender',
    'expiry-date': 'User expiration date',
    search: {
      'form-names-and-tags': 'Search form names and tags',
    },
  },
  common: {
    'read-only': 'read only',
    'automatically-created': 'automatically created',
    'space-separated-location-ids': 'space separated location IDs',
    'cannot-be-changed': 'cannot be changed',
  },
  location: {
    'full-official-name': 'Full official location name',
    address: 'Address',
    'mailing-address': 'Mailing address',
    id: 'Location ID',
    'automatically-created': 'automatically created',
    'entity-type': 'Entity type',
    'create-location': 'Create location',
    'submit-location': 'Submit changes',
    'delete-location': 'Delete location',
    'enable-location': 'Enable location',
    'disable-location': 'Disable location',
    'select-country': 'Select country',
    'any-country': 'Any country',
    'select-language': 'Select language',
    'any-language': 'Any language',
    'select-entity-type': 'Select entity type',
    'any-entity-type': 'Any entity type',
    'select-default-language': 'Select default language',
    'any-default-language': 'Any default language',
    search: 'Search for location ID like ML3-XXX-YYY-ZZZ',
    entity: {
      'medical-facility': 'Medical facility',
      'police-station': 'Police station',
      'refugee-camp': 'Refugee camp',
    },
    'coordinates-instructions':
      'You can get GPS coordinates from Google Maps. Open Google Maps, find the location. Right click on the location. At the top of the menu that opens under the mouse, you will see the coordinates. Click them to copy, then paste them into the box here.',
  },
  'form-editor': {
    title: 'Form title',
    'subtitle-optional': 'Form subtitle (optional)',
    'official-name': 'Official name',
    'official-code': 'Official code',
    'select-country': 'Select country',
    'select-language': 'Select language',
    'select-location': 'Select location',
    priority: 'Priority (0-9)',
    'form-id': 'Form ID (automatically created)',
    version: 'Form version (automatic)',
    'created-on': 'Creation date (automatic)',
    'last-changed': 'Last changed (automatic)',
    id: 'Form ID (automatic)',
    'create-form': 'Create form',
    'submit-form': 'Update form',
    'disable-form': 'Disable form',
    'enable-form': 'Enable form',
  },
  record: {
    filter: {
      'select-record-sealed': 'Sealed or unsealed record',
      'any-is-sealed': 'Any record',
      enabled: 'Sealed records',
      disabled: 'Unsealed records',
    },
    heading: {
      patient: 'Patient',
      form: 'Form',
      'changed-created': 'Changed / Created',
      sealed: 'Sealed',
    },
    'search-by': {
      select: 'Select search type',
      'record-id': 'Record ID',
      'patient-name': 'Patient name',
    },
    'missing-patient-name': 'No patient name recorded',
    'incident-date': 'Incident date',
    overview: {
      'section-title': 'Record Overview',
      'automatically-filled':
        'This information will be automatically filled in as the record is completed.',
      name: 'Name',
      titles: {
        patient: 'Patient details',
        administrative: 'Adminstrative details',
        timeline: 'Timeline',
      },
      'created-date': 'Created date',
      'created-by': 'Created by',
      'last-changed-date': 'Last changed date',
      'last-changed-by': 'Last changed by',
      'record-version': 'Record version',
      'form-id': 'Form ID',
      'form-version': 'Form version',
      'form-title': 'Form title',
      'form-name-and-code': 'Form official name and code',
      'form-tile': 'Form title',
      'case-id': 'Remote case ID',
      'record-id': 'Remote case ID',
    },
  },
  form: {
    filter: {
      'select-form-enabled': 'Enabled or disabled forms',
      'any-is-form-enabled': 'All forms',
      enabled: 'Enabled forms',
      disabled: 'Disabled forms',
    },
    Yes: 'Yes',
    No: 'No',
    'select-value': 'Select a value',
    'other-details': 'Describe other optional details',
    'add-photo': 'Add an existing photo',
    'take-photo': 'Take a new photo',
    'save-photo': 'Save',
    'cancel-photo': 'Cancel',
    'delete-photo': 'Delete photo',
    'mark-diagram': 'Annotate the diagram',
    'repeated-one-time-below': 'repeated one time below',
    'can-repeat-below': 'can repeat below',
    repeated: 'repeated',
    'times-below': 'times below',
    'repeat-number': 'number',
    'repeat-out-of': 'out of',
    'enter-date-time': 'Enter date and time',
    'enter-date': 'Enter date',
    'enter-number': 'Enter number',
    'enter-phone-number': 'Enter phone number',
    'enter-email': 'Enter email',
    'enter-text': 'Enter text',
    'enter-long-text': 'Enter long text',
    'enter-address': 'Enter address',
    'select-other-option': 'Select other option',
    'select-the-option': 'Select the option',
    'skip-question': 'Skip answering this question',
    'camera-viewer': 'Camera view',
  },
  country: {
    AF: 'Afghanistan',
    AX: 'Åland Islands',
    AL: 'Albania',
    DZ: 'Algeria',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua and Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BQ: 'Bonaire, Sint Eustatius and Saba',
    BA: 'Bosnia and Herzegovina',
    BW: 'Botswana',
    BV: 'Bouvet Island',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    BN: 'Brunei',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    CV: 'Cabo Verde',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CI: "Côte d'Ivoire",
    HR: 'Croatia',
    CU: 'Cuba',
    CW: 'Curaçao',
    CY: 'Cyprus',
    CZ: 'Czechia',
    CD: 'Democratic Republic of the Congo',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EE: 'Estonia',
    SZ: 'Eswatini',
    ET: 'Ethiopia',
    FK: 'Falkland Islands',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guinea',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HT: 'Haiti',
    HM: 'Heard Island and McDonald Islands',
    VA: 'Holy See',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JE: 'Jersey',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    KP: "Democratic People's Republic of Korea",
    KR: 'Republic of Korea',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Lao',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macao',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    MK: 'North Macedonia',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestine, State of',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RU: 'Russia',
    RW: 'Rwanda',
    BL: 'Saint Barthélemy',
    SH: 'Saint Helena, Ascension and Tristan da Cunha',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    MF: 'Saint Martin (French)',
    PM: 'Saint Pierre and Miquelon',
    VC: 'Saint Vincent and the Grenadines',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'Sao Tome and Principe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten (Dutch part)',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard and Jan Mayen',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad and Tobago',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks and Caicos Islands',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States of America',
    UM: 'United States Minor Outlying Islands',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VE: 'Venezuela',
    VN: 'Viet Nam',
    VG: 'Virgin Islands (British)',
    VI: 'Virgin Islands (U.S.)',
    WF: 'Wallis and Futuna',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
  },
}
