---
swagger: "2.0"
info:
  description: "The MediCapt API"
  version: "0.1"
  title: "Medicapt API"
  termsOfService: ""
  contact: {}
securityDefinitions:
  ProviderUsers:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: cognito_user_pools
    x-amazon-apigateway-authorizer:
      type: COGNITO_USER_POOLS
      providerARNs:
      - arn:aws:cognito-idp:${region}:${account_id}:userpool/${cognito_user_pool_id}
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /users/{userid}:
    get:
      summary: "Get user"
      parameters: []
      responses:
        200:
          description: "Status 200"
      security:
        - Provider: []
      x-amazon-apigateway-integration:
        uri: ${lambda_uri}
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
    parameters:
    - name: "userid"
      in: "path"
      required: true
      type: "string"
definitions:
  UUID:
    type: "string"
  Error:
    type: "object"
    required:
    - "code"
    properties:
      code:
        type: "integer"
        minimum: 400
        maximum: 599
      description:
        type: "string"
      reasonPhrase:
        type: "string"
    description: "This general error structure is used throughout this API."
  Patient:
    type: "object"
  User:
    type: "object"
    properties:
      metadataAccess:
        type: "array"
        items:
          $ref: "#/definitions/UUID"
      institutionAccess:
        type: "array"
        items:
          $ref: "#/definitions/UUID"
  Instiution:
    type: "object"
